"""empty message

Revision ID: fb32db1ee68a
Revises: 
Create Date: 2024-12-28 02:57:41.468426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb32db1ee68a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booktype_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'types', ['booktype_id'], ['id'])
        batch_op.drop_column('book_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('booktype_id')

    # ### end Alembic commands ###
